### ISSUE TITLE
Shebang with -host flag

### ISSUE THREAD

**Issue by richarvey** [mattn/etcdenv#9]
Hi when running:

```
/home/ec2-user/go/bin/etcdenv -host="http://core01.internal.net:4001" -key="test" -r
```

all works well, however trying to use the shebang example:

```
#!/home/ec2-user/go/bin/etcdenv -host="http://core01.internal.net:4001" -key="test" -r
```

I run 

```
./test.sh
```

and i get this error:

etcdenv: 501: All the given peers are not reachable (failed to propose on members ["http://core01.internal.net:4001" -key="test" -r] twice [last error: Get %22http://core01.internal.net:4001%22%20-key=%22test%22%20-r/v2/keys/?quorum=false&recursive=true&sorted=true: unsupported protocol scheme ""]) [0]

Do you support etcd v2? is that the issue?

**Comment by mattn** [comment]
use `-s` flag. there are some implementations of shebang. one of it doesn't handle arguments that is separated with spaces. so etcdenv provide `-s` option. please try `-s` option.

**Comment by richarvey** [comment]
Thanks for the quick reply mattn,

I've tried with -s here is the result:

etcdenv: 501: All the given peers are not reachable (failed to propose on members ["http://core01.internal.net:4001" -key="test" -r] twice [last error: Get %22http://core01.internal.net:4001%22%20-key=%22test%22%20-r/v2/keys/?quorum=false&recursive=true&sorted=true: unsupported protocol scheme ""]) [0]

I noted I had to remove the "" around the host and key as they were getting converted to %22 and the host lookup was failing.

But then i get this error:

[ec2-user@ip-10-8-0-138 etcdenv]$ ./test.sh
etcdenv: fork/exec ./test.sh: argument list too long

**Comment by mattn** [comment]
probably, you specify -s on last token. right? please try below.

```
#!/home/ec2-user/go/bin/etcdenv -s -host="http://core01.internal.net:4001" -key="test" -r
```

**Comment by mattn** [comment]
BTW, you need to specify commands like below.

```
#!/home/ec2-user/go/bin/etcdenv -s -host="http://core01.internal.net:4001" -key="test" -r perl
```

**Comment by richarvey** [comment]
AHHHHH i missunderstood that sorry. All is now working.
